language: php

php:
  - "5.5"
  - "5.6"
  - "7"
  - "hhvm"

matrix:
  allow_failures:
    - php: "hhvm"

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: 
- vendor/bin/phpcs --standard=ruleset.xml
- vendor/bin/phpunit -c phpunit.xml.dist
